---
name: ncov-qa
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake
  - parasail-python
  - pip=19.3.1
  - numpy=1.19.1
  - pysam
  - snpeff=5.0-0
  - numpy=1.19.1
  - biopython=1.77
  - icu=68.1
  - bedtools
  - samtools
